### ISSUE TITLE
change to popen no longer prints command output to stdout

### ISSUE THREAD

**Issue by jsvd** [logstash-plugins/logstash-output-exec#11] opened 2016-11-02 12:57 UTC
```
/tmp/logstash-2.4.0 % bin/logstash -e "output { exec { command => 'ls' } }" > meh
blabla
/tmp/logstash-2.4.0 % cat meh
{:timestamp=>"2016-11-02T12:39:17.907000+0000", :message=>"Pipeline main started"}
{:timestamp=>"2016-11-02T12:39:38.129000+0000", :message=>"Pipeline main has been shutdown"}
{:timestamp=>"2016-11-02T12:39:38.565000+0000", :message=>"stopping pipeline", :id=>"main"}
```

see more in https://discuss.elastic.co/t/logstash-output-exec-stdout-redirect-impossible/64709

**Comment by zyguy** [comment] 2016-11-25 15:36
👍  
Hi ! Any update for this issue ?

**Comment by jordansissel** [comment] 2016-11-26 01:54
All updates for this issue should appear on this issue. Nothing is hidden.

Does that help answer your update question?

**Comment by zyguy** [comment] 2016-11-28 08:56
Hello, 

Thx a lot ;)

**Comment by magnusbaeck** [comment] 2017-08-20 20:06
I can't reproduce this with Logstash 5.5.1 and the head of the plugin:

```plain
$ echo '' | ~/logstash/logstash-5.5.1/bin/logstash -e "output { exec { command => 'ls' } }"
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
Sending Logstash's logs to /home/magnus/logstash/logstash-5.5.1/logs which is now configured via log4j2.properties
[2017-08-20T21:54:00,906][INFO ][logstash.pipeline        ] Starting pipeline {"id"=>"main", "pipeline.workers"=>8, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>5, "pipeline.max_inflight"=>1000}
[2017-08-20T21:54:00,927][INFO ][logstash.pipeline        ] Pipeline main started
[2017-08-20T21:54:00,968][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2017-08-20T21:54:00,974][INFO ][logstash.outputs.exec    ] CHANGELOG.md
ci
CONTRIBUTORS
docs
Gemfile
Gemfile.lock
lib
LICENSE
logstash-output-exec-3.1.2.gem
logstash-output-exec.gemspec
NOTICE.TXT
Rakefile
README.md
spec
[2017-08-20T21:54:03,943][WARN ][logstash.agent           ] stopping pipeline {:id=>"main"}
```

Given how little this plugin has changed since the issue was filed it's not entirely clear why it's working now when it clearly wasn't working earlier, but I'm going to close this as invalid. Feel free to reopen if this was wrong, but in that case please provide additional details about how to reproduce.

Rereading the discuss.elastic.co thread that initiated this issue I think the point was lost—I believe the reported problem is really about why Logstash doesn't pass the command to a shell. This is covered by #13.

**Closed as completed by magnusbaeck** 2017-08-20 20:06 UTC
Labels: bug, invalid
