### ISSUE TITLE
send all the message to shell script

### ISSUE THREAD

**Issue by robertlrs** [logstash-plugins/logstash-output-exec#16] opened 2018-04-03 09:09 UTC
Here is my config for logstash output:
output {
    stdout {codec => rubydebug}
    if [level] == "ERROR"{
    
        exec {
            command => "send_msg  %{[module]} \"%{[message]}\""
        }   
    }  

send_msg is my shell script， when there is a error message which has multi line like:
  " [2018-04-03 15:51:38.113] article[172.16.6.197] ERROR 2c87099643b7898b 1 null [DubboServerHandler-172.16.6.197:18087-thread-192]
                cn.idongjia.exception.filter.DubboExceptionFilter.invoke(23)
	com.alibaba.dubbo.rpc.RpcException: Failed to invoke the method search in the service cn.idongjia.search.api.res.UGCPCSearchService. Tried 1 times of the providers [172.16.16.229:12811] (1/3) from the registry 172.16.9.43:2182 on the consumer 172.16.6.197 using the dubbo version 2.8.4. Last error is: Invoke remote method timeout. method: search, provider"

    then only message send_msg can receive is “ [2018-04-03 15:51:38.113] article[172.16.6.197] ERROR 2c87099643b7898b 1 null [DubboServerHandler-172.16.6.197:18087-thread-192]”

How can i do if i want to receive all the message?

**Comment by jsvd** [comment] 2018-04-03 09:31
please open only one issue. this is a duplicate of https://github.com/logstash-plugins/logstash-output-exec/issues/16. closing.

**Closed as completed by jsvd** 2018-04-03 09:31 UTC

**Comment by arichiardi** [comment] 2020-10-07 23:55
Hi there, I stumbled upon this one as well and I was wondering if there is a way to pass the whole message, maybe json encoded with this plugin?
